workers_dev = true
type = "javascript"
name = "batom-price-feed-dev"
account_id = "a3a193f983b581d1a73f4a984e117029"

[vars]
ENV = "development"
SENTRY_PROJECT_ID = ""
SENTRY_KEY = ""
DEVIATION_BLOCK_OFFSETS = '[6500,260,40]'
BATOM_RATE_LIMITS = '{}'
BATOM_PRICE_LIMITS = '{"maxDeviations":[60,30,20]}'
STETH_RATE_LIMITS = '{"maxDeviations":[5,1,0.5]}'
ATOM_PRICE_LIMITS = '{}'


[build]
command = "npm run build"

[build.upload]
format = "service-worker"


[env.staging]
workers_dev = false
name = "batom-price-feed-staging"
route = ""
zone_id = ""

[env.staging.vars]
ENV = "staging"
SENTRY_PROJECT_ID = ""
SENTRY_KEY = ""
DEVIATION_BLOCK_OFFSETS = '[6500,260,40]'
BATOM_RATE_LIMITS = '{}'
BATOM_PRICE_LIMITS = '{"maxDeviations":[60,30,20]}'
STETH_RATE_LIMITS = '{"maxDeviations":[5,1,0.5]}'
ATOM_PRICE_LIMITS = '{}'

[env.production]
workers_dev = false
name = "batom-price-feed"
route = ""
zone_id = ""

[env.production.vars]
ENV = "production"
SENTRY_PROJECT_ID = ""
SENTRY_KEY = ""
DEVIATION_BLOCK_OFFSETS = '[6500,260,40]'
BATOM_RATE_LIMITS = '{}'
BATOM_PRICE_LIMITS = '{"maxDeviations":[60,30,20]}'
STETH_RATE_LIMITS = '{"maxDeviations":[5,1,0.5]}'
ATOM_PRICE_LIMITS = '{}'
